import { siteConfig } from "@/data/siteConfig";

export const sevenAssistantData = {
  brand: {
    name: siteConfig.brandName,
    slogan: siteConfig.slogan,
    description: siteConfig.description,
    generalInfo: "Seven Restopub — сучасна українська мережа restopub.",
    mainFocus: [
      "крафтове пиво",
      "їжа",
      "коктейлі",
      "футбол",
      "тераса",
      "кальян",
      "події",
      "банкети",
      "командна атмосфера",
    ],
  },
  venues: [
    {
      id: "lviv-vv",
      name: "Seven Володимира Великого",
      fullName: "Seven Restopub Володимира Великого",
      city: "Львів",
      address: "м. Львів, вул. Володимира Великого, 18",
      phone: "0 (98) 711 77 71",
      workingHours: "щодня 12:00–23:00",
      features: ["дитяча кімната", "тераса", "кальян", "крафтове пиво", "комфорт-фуд", "бізнес-ланчі"],
      menu: "https://seven-restopub-lviv.choiceqr.com/menu",
      instagram: "placeholder",
      mapsLink: "placeholder",
      realInstagram: siteConfig.locations[0].instagram,
      realMapsLink: siteConfig.locations[0].googleMaps,
    },
    {
      id: "lviv-rynok",
      name: "Seven Площа Ринок",
      fullName: "Seven Restopub Площа Ринок",
      city: "Львів",
      address: "м. Львів, площа Ринок, 25",
      phone: "0 (97) 777 73 25",
      workingHours: "щодня 12:00–23:00",
      features: ["центр Львова", "крафтове пиво", "кухня", "кальян", "туристична локація"],
      menu: "https://mytsi.choiceqr.com/",
      instagram: "placeholder",
      mapsLink: "placeholder",
      realInstagram: siteConfig.locations[1].instagram,
      realMapsLink: siteConfig.locations[1].googleMaps,
    },
    {
      id: "zaporizhzhia",
      name: "Seven Запоріжжя",
      fullName: "Seven Restopub Запоріжжя",
      city: "Запоріжжя",
      address: "м. Запоріжжя, вул. Сталеварів, 30",
      phone: "0 (68) 711 77 71",
      workingHours: "щодня 12:00–23:00",
      features: ["крафтове пиво", "закуски", "спорт", "атмосфера restopub"],
      menu: "https://seven-restopub.choiceqr.com/",
      instagram: "placeholder",
      mapsLink: "placeholder",
      realInstagram: siteConfig.locations[2].instagram,
      realMapsLink: siteConfig.locations[2].googleMaps,
    },
  ],
  social: {
    mainInstagram: "placeholder",
    tiktok: "placeholder",
    realMainInstagram: siteConfig.instagram,
    realTikTok: siteConfig.tiktok,
    instagramByVenue: siteConfig.locations.map((location) => ({
      venue: location.name,
      instagram: location.instagram,
    })),
  },
  menuCategories: siteConfig.menuCategories.map((category) => ({
    title: category.title,
    description: category.description,
  })),
  events: siteConfig.events.map((event) => ({
    title: event.title,
    category: event.category,
    description: event.description,
    date: event.date,
  })),
  banquetRules: {
    title: "Банкети у Seven",
    fromPeople: "від 10 людей",
    deposit: "1500 UAH / людина",
    serviceCharge: "+10% service charge",
    corkFee: ["300 UAH — вино або ігристе за пляшку", "500 UAH — міцний алкоголь за пляшку"],
    preOrderRequired: "Для банкетів 10+ людей потрібне попереднє замовлення.",
    source: siteConfig.banquetRules,
  },
  snookball: siteConfig.snookball,
  hr: {
    title: "Стати частиною команди Seven",
    telegram: "https://t.me/Hrsevengroup",
    note: "Кандидати можуть подати заявку через HR-форму на сайті. CV / резюме можна прикріпити опційно. Заявки надходять HR-команді в Telegram.",
    cvUpload: "CV upload is optional.",
    applicationsDestination: "Telegram HR",
    positions: ["Офіціант", "Бармен", "Кухар", "Кальянщик", "Адміністратор", "Інше"],
  },
  bookingPolicy: "Для бронювання столу, банкету або Snookball потрібно телефонувати у вибрану локацію.",
  missingInfoMessage: "Точної інформації зараз немає, краще уточнити у закладі.",
} as const;

export function getSevenAssistantContext() {
  return JSON.stringify(sevenAssistantData, null, 2);
}
